-- AlterTable
ALTER TABLE "Item" ALTER COLUMN "minimumAreaMm2" SET DATA TYPE BIGINT,
ALTER COLUMN "totalAreaMm2" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "areaMm2" SET DATA TYPE BIGINT;
